version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: arbitrage_bot
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: secure_password_123
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: unless-stopped

  arbitrage_bot:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://bot_user:secure_password_123@postgres:5432/arbitrage_bot
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    restart: unless-stopped